export {
  NOTIFICATION_KINDS,
  SEVERITIES,
  meetsSeverity,
  type NotificationKind,
  type Severity,
} from "./kinds.js";
export {
  raiseForSupervisors,
  raiseNotification,
  type RaiseInput,
  type RaiseResult,
} from "./raise.js";
export {
  DELIVERY_HEADER,
  EVENT_HEADER,
  SIGNATURE_HEADER,
  TIMESTAMP_HEADER,
  WebhookSender,
  classifyStatus,
  signWebhook,
  signingMaterial,
  verifyWebhook,
  type ChannelSender,
  type EndpointConfig,
  type FetchLike,
  type SendOutcome,
  type WebhookPayload,
  type WebhookSenderOptions,
} from "./sender.js";
export {
  MAX_ATTEMPTS,
  NotificationDispatcher,
  claimDue,
  markDead,
  markDelivered,
  markRetry,
  nextDelayMs,
  settleOrphanedDeliveries,
  type ClaimedDelivery,
  type DispatchResult,
  type NotificationDispatcherOptions,
} from "./dispatch.js";
export { inbox, markAllRead, markRead, unreadCount, type InboxItem } from "./inbox.js";
export {
  ENDPOINT_CHANNELS,
  InvalidEndpointError,
  createEndpoint,
  getEndpoint,
  isSeverity,
  listEndpoints,
  updateEndpoint,
  type CreateEndpointInput,
  type EndpointChannel,
  type EndpointRow,
  type UpdateEndpointInput,
} from "./endpoints.js";
export {
  DEFAULT_PRUNE_GUARD_FLOOR_ROWS,
  DEFAULT_PRUNE_MAX_SHARE_PERCENT,
  DEFAULT_RETAIN_DELIVERY_DAYS,
  DEFAULT_RETAIN_READ_DAYS,
  DEFAULT_RETAIN_UNREAD_DAYS,
  InvalidRetentionError,
  MAX_PRUNE_GUARD_FLOOR_ROWS,
  MAX_PRUNE_OVERRIDE_BY_CHARS,
  MAX_PRUNE_OVERRIDE_HOURS,
  MAX_PRUNE_ROWS,
  grantPruneGuardOverride,
  notificationDeliveryRetention,
  notificationPolicy,
  notificationPruneGuard,
  prunableNotifications,
  pruneNotifications,
  prunePreview,
  revokePruneGuardOverride,
  setNotificationDeliveryRetention,
  setNotificationPolicy,
  setNotificationPruneGuard,
  type DeliveryPruneOutcome,
  type DeliveryPrunePreview,
  type DeliveryRetention,
  type NotificationPolicy,
  type PruneCandidate,
  type PruneGuard,
  type PrunePreview,
  type PruneResult,
} from "./retention.js";
export {
  deliveryHistory,
  recentDeliveries,
  type DeliveryRecord,
} from "./delivery-history.js";
export {
  CHANNEL_COVERAGE_VERDICTS,
  assessChannelCoverage,
  checkChannelCoverage,
  endpointChannelUsage,
  type ChannelCoverage,
  type ChannelCoverageReport,
  type ChannelCoverageVerdict,
  type EndpointChannelUsage,
} from "./channel-coverage.js";
export {
  DEFAULT_PROBE_BUDGET_MAX_PROBES,
  DEFAULT_PROBE_BUDGET_WINDOW_SECONDS,
  DEFAULT_PROBE_COOLDOWN_SECONDS,
  EndpointNotFoundError,
  ProbeRequesterNotFoundError,
  EndpointProbeRunner,
  InvalidProbeBudgetError,
  InvalidProbeCooldownError,
  MAX_PROBE_ATTEMPTS,
  MAX_PROBE_BUDGET_MAX_PROBES,
  MAX_PROBE_BUDGET_WINDOW_SECONDS,
  MAX_PROBE_COOLDOWN_SECONDS,
  MIN_PROBE_BUDGET_MAX_PROBES,
  MIN_PROBE_BUDGET_WINDOW_SECONDS,
  PROBE_EVENT,
  PROBE_LEASE_MS,
  PROBE_STATES,
  PROBE_VERDICTS,
  ProbeBudgetExceededError,
  ProbeCooldownError,
  ProbeInFlightError,
  SmtpProber,
  WebhookProber,
  claimDueProbes,
  latestProbe,
  listProbes,
  probeBody,
  probeById,
  probeBudget,
  probeCooldownSeconds,
  recordProbeVerdict,
  requestProbe,
  setProbeBudget,
  setProbeCooldownSeconds,
  type ChannelProber,
  type ClaimedProbe,
  type EndpointProbeRunnerOptions,
  type ProbeBudgetState,
  type ProbeOutcome,
  type ProbeRow,
  type ProbeRunResult,
  type ProbeState,
  type ProbeTarget,
  type ProbeVerdict,
  type RequestProbeInput,
  type SmtpProberOptions,
  type WebhookProberOptions,
} from "./probe.js";

/**
 * The SMTP sender. `testing-smtp.ts` is deliberately NOT re-exported: it is a test
 * double, and the one test helper this repo does publish (`@crm/db/testing`) does it
 * through its own subpath export rather than the main barrel.
 */
export {
  InvalidMailEndpointError,
  InvalidSmtpRelayError,
  SMTP_EXPECTED,
  SMTP_STAGES,
  SmtpProtocolError,
  SmtpSender,
  SmtpTimeoutError,
  classifySmtpReply,
  type SmtpRelayConfig,
  type SmtpSenderOptions,
  type SmtpStage,
  type SmtpTransport,
} from "./smtp.js";
